### PR TITLE
generate: pass through correct name of schema provider

### LINKED ISSUE #139: No Schema Discovery when using Resource/Data-Source specific templates
Not sure if I have the wrong expectation or if something is broken with resource and data-source templates. The template line:

{{ .SchemaMarkdown | trimspace }} seems to break/not-function when I create these specific templates.

I have my internal/provider/resource_plugin.go and internal/provider/datasource_plugin.go files defined. I create templates:

templates/resource/plugin.md.tmpl and templates/data-sources/plugin.md.tmpl

run tfplugindocs in the root of my plugin repo and get an error:

`Error executing command: unable to generate website: unable to render template "data-sources/plugin.md.tmpl": unable to execute template: template: docTemplate:11:21: executing "docTemplate" at <trimspace>: invalid value; expected string
`

This trimspace error is related to .SchemaMarkdown return "<no value>". Seems that .SchemaMarkdown can't find the 

`func resourcePlugin() *schema.Resource` in resource_plugin.go (nor datasource_plugin.go). 

If I don't create specific templates, tfplugindocs runs to completion and all the files are generated. Although without the custom content I'd like to include.

I'm expecting my specific templates to allow me to create custom md-headers and other content, while .SchemaMarkdown does it's thing.

Creating the specific template index.md.tmpl works as I expect.

Is this how templates/resource/plugin.md.tmpl and templates/datasources/plugin.md.tmpl are suposed to work? 

Thank you.

### PR DESCRIPTION
**Pull request by jacobbednarz**
After updating to 0.9.0, I found that individual template overrides no
longer worked using the `generate` command however, would work if using
`tfplugindocs` directly. I started looking into why this was and it
boiled down to being that the value from `--rendered-provider-name` was
being incorrectly passed into `resourceSchema` causing the friendly name
(such as `Cloudflare`) to be used instead of the correct schema name
(here, `terraform-provider-cloudflare`) resulting in the schema never
being found for the data-source or resource. This corrects the value we
pass to the render website methods to always be the schema provider, not
the friendly name.

Closes #139

### CODE REVIEW

**Review by detro — APPROVED** [review]
I can see that this is the first step: I was looking at this change, and it essentially results in no use of that `renderedProviderName`.

But in #149 you kinda close the circle, and it makes sense.

**Comment by jacobbednarz** [comment]
yep! I'm also leaving the default in the template as I don't think we want this as the default anywhere (even with a fallback) just yet. ideally, people can choose to customise it going forward and it will be work but not forced on anyone.

File: internal/provider/generate.go [hunk 1]
```diff
@@ -170,13 +170,13 @@ func (g *generator) Generate(ctx context.Context) error {
...
 	g.infof("rendering missing docs")
-	err = g.renderMissingDocs(g.renderedProviderName, providerSchema)
+	err = g.renderMissingDocs(providerName, providerSchema)
 	if err != nil {
 		return err
 	}
 
 	g.infof("rendering static website")
-	err = g.renderStaticWebsite(g.renderedProviderName, providerSchema)
+	err = g.renderStaticWebsite(providerName, providerSchema)
```
Comment (elXaptation) [inline internal/provider/generate.go:179]: Perhaps this line shouldn't have change??

Comment (elXaptation) [reply internal/provider/generate.go:179]: Scratch that.. Doesn't seem to make a difference.
